name: Build Transcriber

on:
  push:
    tags:
      - 'v*'   # Ex: v1.0.0 para gerar release
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install pyinstaller torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          pip install git+https://github.com/openai/whisper.git

      - name: Baixar modelo Whisper base
        run: |
          python -c "import whisper; whisper.load_model('base')"

      - name: Gerar executável com PyInstaller
        run: |
          pyinstaller transcriber.py --onefile --noconsole \
            --add-data "$HOME/.cache/whisper:whisper_cache"

      - name: Renomear executável
        run: |
          mkdir release
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/transcriber.exe release/transcriber-windows.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/transcriber release/transcriber-macos
          else
            mv dist/transcriber release/transcriber-linux
          fi

      - name: Empacotar ZIP
        run: |
          cd release
          zip -r transcriber-${{ runner.os }}.zip ./*

      - name: Upload como artefato
        uses: actions/upload-artifact@v4
        with:
          name: transcriber-${{ runner.os }}
          path: release/transcriber-${{ runner.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Baixar artefatos
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Criar release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/transcriber-windows/transcriber-windows.zip
            artifacts/transcriber-macos/transcriber-macos.zip
            artifacts/transcriber-linux/transcriber-linux.zip
